#!/bin/sh

sudo pacman -Syu --noconfirm
sudo pacman -S --noconfirm git python ansible

pushd /vagrant/provision
ansible-galaxy install -r ./requirements.yml -p ./vendor/roles
ansible-playbook ./site.yml
